// Generated by CoffeeScript 1.10.0
var duiHelper;

duiHelper = {
  baseUrl: 'http://' + window.location.host + '/bi/component',
  getCondition: function(conditions) {
    var condtionMap = {};
    $(conditions).each(function() {
      var $this = $(this),
        name = $this.attr('name'),
        value = $this.data('value');
      if (typeof value === 'undefined' || value === null) {
        value = $this.val();
      }
      if (typeof value === 'undefined' || value === null || value === '') {
        return;
      }
      if ($this.data('quote')) {
        value = '\'' + value + '\'';
      }

      if (typeof $this.attr('condition-group') !== 'undefined') {
        var groupName = $this.attr('condition-group');
        var gValue = condtionMap[groupName];
        if (typeof gValue === 'undefined' || gValue === null) {
        	condtionMap[groupName] =  name + '=' + value;
        } else{
        	condtionMap[groupName] +=  ' and ' + name + '=' + value;
        }
      }else{
        condtionMap[name] = value;
      }
    });
    var condiontArray = [];
    for ( var p in condtionMap ){
      condiontArray.push('c_' + p + '=' + encodeURIComponent(condtionMap[p]));
    }
    return condiontArray.join('&');
  },
  load: (function(_this) {
    return function(arg) {
      var cid, condition, ref, container;
      container = arg.container, cid = arg.cid, condition = (ref = arg.condition) != null ? ref : '';
      return $(container).load(duiHelper.baseUrl + "/pcs_" + cid + "?" + condition, function() {
        return $(container).find('.dui-component').trigger('loaded.tbl.dui', [container]);
      });
    };
  })(this)
};
